export const adminNav = [
  { label: "01 Dashboard", to: "/admin/dashboard" },
  { label: "02 Customers", to: "/admin/customers" },
  { label: "03 Sales Team", to: "/admin/sales-team" },
  { label: "04 Requests", to: "/admin/requests" },
  { label: "04A Support", to: "/admin/support" },
  { label: "05 Aircraft", to: "/admin/aircraft" },
  { label: "06 Yachts", to: "/admin/yachts" },
  { label: "07 Operators", to: "/admin/operators" },
  { label: "08 Quotes", to: "/admin/quotes" },
  { label: "09 Bookings", to: "/admin/bookings" },
  { label: "10 Voice Assistant", to: "/admin/voice" },
  { label: "11 Analytics", to: "/admin/analytics" },
  { label: "12 Pricing", to: "/admin/pricing" },
  { label: "13 Content", to: "/admin/content" },
  { label: "14 Notifications", to: "/admin/notifications" },
  { label: "15 Audit Logs", to: "/admin/audit" },
  { label: "16 Settings", to: "/admin/settings" },
] as const;

export const customerNav = [
  { label: "01 Dashboard", to: "/customer/dashboard" },
  { label: "01A Subscription & Credits", to: "/customer/subscriptions" },
  { label: "02 New Request", to: "/customer/requests/new" },
  { label: "02A Events", to: "/customer/events" },
  { label: "03 My Requests", to: "/customer/requests" },
  { label: "04 Quotes", to: "/customer/quotes" },
  { label: "05 Bookings", to: "/customer/bookings" },
  { label: "06 Notifications", to: "/customer/notifications" },
  { label: "07 Support", to: "/customer/support" },
  { label: "08 Documents", to: "/customer/documents" },
  { label: "09 Profile", to: "/customer/profile" },
] as const;

export const salesNav = [
  { label: "01 Dashboard", to: "/sales/dashboard" },
  { label: "02 Requests", to: "/sales/requests" },
  { label: "03 My Requests", to: "/sales/my-requests" },
  { label: "04 Customers", to: "/sales/customers" },
  { label: "05 Aviation", to: "/sales/aviation" },
  { label: "06 Yachts", to: "/sales/yachts" },
  { label: "07 Quotes", to: "/sales/quotes" },
  { label: "08 Bookings", to: "/sales/bookings" },
  { label: "09 Messages", to: "/sales/messages" },
  { label: "10 Follow-ups", to: "/sales/followups" },
  { label: "11 Documents", to: "/sales/documents" },
  { label: "12 Profile", to: "/sales/profile" },
  { label: "13 Support", to: "/sales/support" },
] as const;
